rm hispanic vs
nightingaleproject/vital_records_sheets pull request #3
Opened 2024-06-12 19:00 UTC by rpassas

Updates from VRCL - removed hispanic no unknown vs

2024-06-12 19:08 UTC, ptran265 requested changes

2024-06-12 19:08 UTC, ptran265 commented on IJE_File_Layouts_Version_2021_FHIR-2023-02-22-All-Combined.csv
> +P = Planned",,BFDR,ObservationHistologicalPlacentalExamPerformed,value,codeable,[HistologicalPlacentalExaminationVS],B,,,,,Observation-histological-placental-exam-performed,
[PerformedNotPerformedPlannedVS] is the correct VS. Is this the latest master sheet pulled from the nightingale repo?

2024-06-14 16:00 UTC, rpassas commented on IJE_File_Layouts_Version_2021_FHIR-2023-02-22-All-Combined.csv
> +P = Planned",,BFDR,ObservationHistologicalPlacentalExamPerformed,value,codeable,[HistologicalPlacentalExaminationVS],B,,,,,Observation-histological-placental-exam-performed,
It should be - not sure why only this one instance of the `PerformedNotPerformedPlannedVS` did not make it in. I pushed a change to fix that + pull in other changes made in VRDR:

- STATESP additional row
- comments on void/alias

2024-06-17 12:58 UTC, ptran265 approved these changes

2024-06-17 14:01 UTC, merged